openapi: 3.0.3
info:
  title: Contact Preferences External API
  description: External API operations of Contact Preferences
  version: v1.0
paths:
  /api/prudential-emails:
    post:
      summary: Add prudential emails
      description: Add Email in Prudential DNC List
      requestBody:
        description: Add Prudential Email request model
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrudentialEmailsRequest'
      responses:
        "200":
          description: "Targets was successfully saved"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OkMessage'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
        "400":
          description: "Missing target value"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrudentialEmailBadRequestResponse'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
        "500":
          description: "Exception message"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostTargetDncListFunction.Arn}/invocations
        requestTemplates:
          application/json: |
            #set($inputRoot = $input.path('$'))
            {
              "path": "$context.resourcePath",
              "body": "{\"targets\":[{\"value\":\"$inputRoot.email\",\"dncList\":\"Prudential\",\"channel\":1,\"isActive\":true}]}",
              "headers": {
                #foreach($param in $input.params().header.keySet())
                "$param": "$util.escapeJavaScript($input.params().header.get($param))",
                #end
                "source-key": "$util.escapeJavaScript($input.params().header.get('x-api-key'))"
              }
            }
        responses:
          '200':
            statusCode: "200"
            responseTemplates: 
              application/json: $input.path('$').body
          '400':
            statusCode: "400"
            responseTemplates: 
              application/json: $input.path('$').body
          default:
            statusCode: "500"
            responseTemplates: 
              application/json: $input.path('$').body
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws"

components:
  schemas:
    PrudentialEmailsRequest:
      type: object
      properties:
        email:
          type: string
          example: "email@prudential.com"
    PrudentialEmailBadRequestResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        type:
          type: string
          example: "validation"
        title:
          type: string
          example: "A validation error occurred"
        detail:
          type: string
          example: "Missing field"
        instance:
          type: string
          example: "/api/prudentials-emails"
        problems:
          type: array
          $ref: '#/components/schemas/TargetDncListError'
    Target:
      type: object
      properties:
        value:
          type: string
          example: "2017743684"
        dncList:
          type: string
          example: Prudential
        channel:
          type: integer
          enum: [0, 1, 2, 3]
          description: 0 Dial, 1 Email, 2 Text, 3 Mail
          example: 0
        isActive:
          type: boolean
          example: true
    TargetDncListError:
      type: object
      properties:
        errorMessage:
          type: string
          example: "Missing target value"
        target:
          type: object
          $ref: '#/components/schemas/Target'
    BadRequestResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        type:
          type: string
          example: "validation"
        title:
          type: string
          example: "A validation error occurred"
        detail:
          type: string
          example: "Missing source"
        instance:
          type: string
          example: "/api/prudentials-emails"
    OkMessage:
      type: string
    ErrorMessage:
      type: string